import type { AppLang } from "@/i18n/translations";

export type SurveyValue = string | string[] | null;
export type SurveyData = Record<string, SurveyValue>;

export type ChipOption = {
  label: string;
  value: string;
  className?: string;
};

export type Question =
  | {
      kind: "chips";
      key: string;
      label: string;
      required?: boolean;
      mode: "single" | "multi";
      options: ChipOption[];
    }
  | {
      kind: "inputs";
      fields: Array<{
        key: string;
        label: string;
        type: "text" | "number";
        placeholder?: string;
      }>;
    }
  | { kind: "textarea"; key: string; label: string; placeholder?: string };

export type Step = {
  id: number;
  title: string;
  desc: string;
  questions: Question[];
};

export const TOTAL_SECTIONS = 13;

export const stepsByLang: Record<AppLang, Step[]> = {
  en: [
    {
      id: 1,
      title: "Basic Building Information",
      desc: "Start with foundational details about the property being assessed.",
      questions: [
        {
          kind: "chips",
          key: "buildingType",
          label: "Type of building",
          required: true,
          mode: "single",
          options: [
            { label: "Apartment", value: "Apartment" },
            { label: "House", value: "House" },
            { label: "Commercial", value: "Commercial" },
            { label: "Basement / Garage", value: "Basement/Garage" },
            { label: "Other", value: "Other" },
          ],
        },
        {
          kind: "chips",
          key: "constructionType",
          label: "Type of construction",
          mode: "multi",
          options: [
            { label: "Concrete", value: "Concrete" },
            { label: "Brick", value: "Brick" },
            { label: "Stone", value: "Stone" },
            { label: "Timber frame", value: "Timber frame" },
            { label: "Solid wall", value: "Solid wall" },
            { label: "Cavity wall", value: "Cavity wall" },
            { label: "Mixed", value: "Mixed" },
          ],
        },
        {
          kind: "chips",
          key: "ownership",
          label: "Type of ownership",
          mode: "single",
          options: [
            { label: "Owner", value: "Owner" },
            { label: "Tenant", value: "Tenant" },
            { label: "Rental property", value: "Rental property" },
            { label: "Social housing", value: "Social housing" },
          ],
        },
        {
          kind: "inputs",
          fields: [
            {
              key: "yearBuilt",
              label: "Year of Construction",
              type: "number",
              placeholder: "e.g. 1978",
            },
            {
              key: "buildingArea",
              label: "Building Area (m²)",
              type: "number",
              placeholder: "e.g. 120",
            },
            {
              key: "floorsAffected",
              label: "Number of Floors Affected",
              type: "number",
              placeholder: "e.g. 2",
            },
            {
              key: "location",
              label: "Address / Location",
              type: "text",
              placeholder: "City or area",
            },
          ],
        },
        {
          kind: "chips",
          key: "floodRisk",
          label: "Elevation / Flood risk",
          mode: "single",
          options: [
            { label: "Low risk", value: "Low risk" },
            { label: "Medium risk", value: "Medium risk" },
            { label: "High / flood zone", value: "High / flood zone" },
            { label: "Unknown", value: "Unknown" },
          ],
        },
      ],
    },
    {
      id: 2,
      title: "Building Characteristics",
      desc: "Moisture-relevant structural and material features of the building.",
      questions: [
        {
          kind: "chips",
          key: "wallMaterials",
          label: "Wall materials",
          mode: "multi",
          options: [
            { label: "Brick", value: "Brick" },
            { label: "Stone", value: "Stone" },
            { label: "Concrete block", value: "Concrete block" },
            { label: "Sand/cement render", value: "Sand/cement render" },
            { label: "Lime render", value: "Lime render" },
            { label: "Porous masonry", value: "Porous masonry" },
            { label: "Non-porous cladding", value: "Non-porous cladding" },
          ],
        },
        {
          kind: "chips",
          key: "dpcPresent",
          label: "DPC (Damp Proof Course) present?",
          mode: "single",
          options: [
            { label: "Yes – physical DPC", value: "Yes – physical DPC" },
            { label: "Yes – chemical injection", value: "Yes – chemical injection" },
            { label: "No DPC", value: "No DPC" },
            { label: "Unknown", value: "Unknown" },
          ],
        },
        {
          kind: "chips",
          key: "dpcCondition",
          label: "DPC condition",
          mode: "single",
          options: [
            { label: "Intact / functioning", value: "Intact / functioning" },
            { label: "Bridged or bypassed", value: "Bridged or bypassed" },
            { label: "Failed / degraded", value: "Failed / degraded" },
            { label: "Cannot determine", value: "Cannot determine" },
          ],
        },
        {
          kind: "chips",
          key: "floorType",
          label: "Floor construction type",
          mode: "single",
          options: [
            { label: "Solid concrete slab", value: "Solid concrete slab" },
            { label: "Suspended timber", value: "Suspended timber" },
            { label: "Beam & block", value: "Beam & block" },
            { label: "Mixed", value: "Mixed" },
          ],
        },
        {
          kind: "chips",
          key: "roofType",
          label: "Roof construction",
          mode: "multi",
          options: [
            { label: "Pitched – tiles", value: "Pitched – tiles" },
            { label: "Pitched – slate", value: "Pitched – slate" },
            { label: "Flat roof membrane", value: "Flat roof membrane" },
            { label: "EPDM / felt flat", value: "EPDM / felt flat" },
            { label: "Green roof", value: "Green roof" },
          ],
        },
        {
          kind: "chips",
          key: "glazing",
          label: "Glazing type",
          mode: "single",
          options: [
            { label: "Single glazed", value: "Single glazed" },
            { label: "Double glazed", value: "Double glazed" },
            { label: "Triple glazed", value: "Triple glazed" },
            { label: "Mixed", value: "Mixed" },
          ],
        },
        {
          kind: "chips",
          key: "groundLevel",
          label: "Ground level vs internal floor",
          mode: "single",
          options: [
            { label: "External lower (normal)", value: "External lower (normal)" },
            { label: "External at same level", value: "External at same level" },
            { label: "External higher (bridging risk)", value: "External higher (bridging risk)" },
          ],
        },
        {
          kind: "chips",
          key: "subfloorVent",
          label: "Subfloor ventilation",
          mode: "single",
          options: [
            { label: "Adequate grilles – clear", value: "Adequate grilles – clear" },
            { label: "Grilles present – blocked", value: "Grilles present – blocked" },
            { label: "No grilles / vents", value: "No grilles / vents" },
            { label: "N/A (solid floor)", value: "N/A (solid floor)" },
          ],
        },
        {
          kind: "chips",
          key: "wallThickness",
          label: "Wall thickness",
          mode: "single",
          options: [
            { label: "<200mm (thin)", value: "<200mm (thin)" },
            { label: "200–300mm", value: "200–300mm" },
            { label: "300–500mm (solid)", value: "300–500mm (solid)" },
            { label: ">500mm (thick stone)", value: ">500mm (thick stone)" },
          ],
        },
      ],
    },
    {
      id: 3,
      title: "External Moisture Ingress Points",
      desc: "Identify external defects that may allow water into the building.",
      questions: [
        {
          kind: "chips",
          key: "roofCondition",
          label: "Roof condition",
          mode: "multi",
          options: [
            { label: "Good – no defects", value: "Good – no defects" },
            { label: "Missing/broken tiles", value: "Missing/broken tiles" },
            { label: "Defective flashings", value: "Defective flashings" },
            { label: "Chimney pointing failed", value: "Chimney pointing failed" },
            { label: "Valley defects", value: "Valley defects" },
            { label: "Active leak confirmed", value: "Active leak confirmed" },
          ],
        },
        {
          kind: "chips",
          key: "gutters",
          label: "Gutters & downpipes",
          mode: "multi",
          options: [
            { label: "Clear and functioning", value: "Clear and functioning" },
            { label: "Blocked gutters", value: "Blocked gutters" },
            { label: "Leaking joints", value: "Leaking joints" },
            { label: "Overflowing", value: "Overflowing" },
            { label: "Downpipe discharging near wall", value: "Downpipe discharging near wall" },
            { label: "Missing sections", value: "Missing sections" },
          ],
        },
        {
          kind: "chips",
          key: "externalWallDefects",
          label: "External wall defects",
          mode: "multi",
          options: [
            { label: "No defects", value: "No defects" },
            { label: "Failed pointing", value: "Failed pointing" },
            { label: "Render cracks", value: "Render cracks" },
            { label: "Masonry spalling", value: "Masonry spalling" },
            { label: "No waterproofing", value: "No waterproofing" },
            { label: "Crack at DPC level", value: "Crack at DPC level" },
          ],
        },
        {
          kind: "chips",
          key: "windowDefects",
          label: "Window & door junctions",
          mode: "multi",
          options: [
            { label: "All sealed – good", value: "All sealed – good" },
            { label: "Failed seals/beading", value: "Failed seals/beading" },
            { label: "Missing sill or drip", value: "Missing sill or drip" },
            { label: "Cracked lintels", value: "Cracked lintels" },
            { label: "Defective flashing at head", value: "Defective flashing at head" },
          ],
        },
        {
          kind: "chips",
          key: "drainage",
          label: "Landscaping & site drainage",
          mode: "multi",
          options: [
            { label: "Ground slopes away – good", value: "Ground slopes away – good" },
            { label: "Ground slopes toward building", value: "Ground slopes toward building" },
            { label: "Standing water observed", value: "Standing water observed" },
            { label: "Paved area causing bridging", value: "Paved area causing bridging" },
            { label: "Soil raised above DPC", value: "Soil raised above DPC" },
          ],
        },
        {
          kind: "chips",
          key: "externalPlumbing",
          label: "External plumbing issues",
          mode: "multi",
          options: [
            { label: "No issues", value: "No issues" },
            { label: "Known pipe burst history", value: "Known pipe burst history" },
            { label: "Suspected leak", value: "Suspected leak" },
            { label: "Drainage failure", value: "Drainage failure" },
          ],
        },
        {
          kind: "textarea",
          key: "externalNotes",
          label: "Additional notes on external defects",
          placeholder: "Describe any specific external observations, locations, severity...",
        },
      ],
    },
    {
      id: 4,
      title: "Internal Signs of Damp & Mould",
      desc: "Document visible internal evidence of moisture problems.",
      questions: [
        {
          kind: "chips",
          key: "visibleSigns",
          label: "Visible signs present",
          mode: "multi",
          options: [
            { label: "Tide marks / staining", value: "Tide marks / staining" },
            { label: "Black mould", value: "Black mould" },
            { label: "Green/white mould", value: "Green/white mould" },
            { label: "Peeling paint/plaster", value: "Peeling paint/plaster" },
            { label: "Efflorescence (salt deposits)", value: "Efflorescence (salt deposits)" },
            { label: "Musty odour", value: "Musty odour" },
            { label: "No visible signs", value: "No visible signs" },
          ],
        },
        {
          kind: "chips",
          key: "locations",
          label: "Locations / rooms affected",
          mode: "multi",
          options: [
            { label: "Ground floor walls – base", value: "Ground floor walls – base" },
            { label: "Upper wall areas", value: "Upper wall areas" },
            { label: "Ceiling", value: "Ceiling" },
            { label: "Floor surface", value: "Floor surface" },
            { label: "Skirtings", value: "Skirtings" },
            { label: "Corners", value: "Corners" },
            { label: "Behind furniture", value: "Behind furniture" },
            { label: "Bathroom/kitchen", value: "Bathroom/kitchen" },
            { label: "Basement/cellar", value: "Basement/cellar" },
          ],
        },
        {
          kind: "chips",
          key: "condensation",
          label: "Condensation evidence",
          mode: "multi",
          options: [
            { label: "None observed", value: "None observed" },
            { label: "On windows", value: "On windows" },
            { label: "On cold pipes", value: "On cold pipes" },
            { label: "On cold wall surfaces", value: "On cold wall surfaces" },
            { label: "On ceilings", value: "On ceilings" },
          ],
        },
        {
          kind: "chips",
          key: "timberDecay",
          label: "Timber decay / insect activity",
          mode: "multi",
          options: [
            { label: "None", value: "None" },
            { label: "Wet rot", value: "Wet rot" },
            { label: "Dry rot", value: "Dry rot" },
            { label: "Fungal growth", value: "Fungal growth" },
            { label: "Active woodworm", value: "Active woodworm" },
            { label: "Inactive woodworm", value: "Inactive woodworm" },
          ],
        },
        {
          kind: "chips",
          key: "floodHistory",
          label: "Internal flooding / pooling history",
          mode: "single",
          options: [
            { label: "No history", value: "No history" },
            { label: "Single event", value: "Single event" },
            { label: "Recurring events", value: "Recurring events" },
            { label: "Currently affected", value: "Currently affected" },
          ],
        },
        {
          kind: "textarea",
          key: "internalNotes",
          label: "Internal observations / notes",
          placeholder:
            "Detail specific room locations, heights of damage, colours of mould, approx affected area m²...",
        },
      ],
    },
    {
      id: 5,
      title: "Moisture Measurements & Profiling",
      desc: "Record instrumental readings and moisture data from the survey.",
      questions: [
        {
          kind: "chips",
          key: "meterType",
          label: "Moisture meter type used",
          mode: "multi",
          options: [
            { label: "Pin meter", value: "Pin meter" },
            { label: "Non-invasive / RF meter", value: "Non-invasive / RF meter" },
            { label: "Both", value: "Both" },
            { label: "Not used", value: "Not used" },
          ],
        },
        {
          kind: "chips",
          key: "mcBase",
          label: "Moisture content (MC%) readings at base of wall",
          mode: "single",
          options: [
            { label: "Dry (<10%)", value: "Dry (<10%)" },
            { label: "Slightly damp (10–15%)", value: "Slightly damp (10–15%)" },
            { label: "Damp (15–20%)", value: "Damp (15–20%)" },
            { label: "Very wet (>20%)", value: "Very wet (>20%)" },
            { label: "Not measured", value: "Not measured" },
          ],
        },
        {
          kind: "chips",
          key: "moistureHeight",
          label: "Height profile of moisture rise",
          mode: "single",
          options: [
            { label: "<300mm (very low)", value: "<300mm (very low)" },
            { label: "300–600mm", value: "300–600mm" },
            { label: "600mm–1m", value: "600mm–1m" },
            { label: ">1m (high rise)", value: ">1m (high rise)" },
            { label: "Uniform (not rising damp)", value: "Uniform (not rising damp)" },
            { label: "Not measured", value: "Not measured" },
          ],
        },
        {
          kind: "chips",
          key: "rh",
          label: "Relative Humidity (%RH) measured",
          mode: "single",
          options: [
            { label: "Below 60% – acceptable", value: "Below 60% – acceptable" },
            { label: "60–70% – elevated", value: "60–70% – elevated" },
            { label: "70–80% – high", value: "70–80% – high" },
            { label: ">80% – very high", value: ">80% – very high" },
            { label: "Not measured", value: "Not measured" },
          ],
        },
        {
          kind: "chips",
          key: "thermal",
          label: "Thermal imaging / infrared survey",
          mode: "single",
          options: [
            { label: "Performed – no anomalies", value: "Performed – no anomalies" },
            { label: "Performed – cold bridges found", value: "Performed – cold bridges found" },
            { label: "Performed – hidden moisture found", value: "Performed – hidden moisture found" },
            { label: "Not performed", value: "Not performed" },
          ],
        },
        {
          kind: "chips",
          key: "saltTest",
          label: "Hygroscopic/salt analysis performed?",
          mode: "single",
          options: [
            { label: "Yes – negative (no significant salts)", value: "Yes – negative (no significant salts)" },
            { label: "Yes – positive (nitrates detected)", value: "Yes – positive (nitrates detected)" },
            { label: "Yes – positive (chlorides detected)", value: "Yes – positive (chlorides detected)" },
            { label: "Yes – high levels (lab confirmed)", value: "Yes – high levels (lab confirmed)" },
            { label: "Not performed", value: "Not performed" },
          ],
        },
        {
          kind: "textarea",
          key: "measurementNotes",
          label: "Measurement notes & readings",
          placeholder:
            "Record specific readings, locations, dew point, surface temperatures, moisture mapping sketch description...",
        },
      ],
    },
    {
      id: 6,
      title: "Ventilation, Humidity & Environment",
      desc: "Assess ventilation systems and environmental conditions in the building.",
      questions: [
        {
          kind: "chips",
          key: "ventType",
          label: "Type of ventilation present",
          mode: "multi",
          options: [
            { label: "Natural – openable windows", value: "Natural – openable windows" },
            { label: "Mechanical extractor fans", value: "Mechanical extractor fans" },
            { label: "Trickle vents in frames", value: "Trickle vents in frames" },
            { label: "Subfloor air bricks", value: "Subfloor air bricks" },
            { label: "MVHR (heat recovery)", value: "MVHR (heat recovery)" },
            { label: "PIV (positive input)", value: "PIV (positive input)" },
            { label: "No ventilation", value: "No ventilation" },
          ],
        },
        {
          kind: "chips",
          key: "ventEffectiveness",
          label: "Ventilation effectiveness",
          mode: "single",
          options: [
            { label: "Adequate", value: "Adequate" },
            { label: "Partially adequate", value: "Partially adequate" },
            { label: "Inadequate", value: "Inadequate" },
            { label: "Very poor / none", value: "Very poor / none" },
          ],
        },
        {
          kind: "chips",
          key: "humidSources",
          label: "Indoor humidity sources",
          mode: "multi",
          options: [
            { label: "High occupancy", value: "High occupancy" },
            { label: "Cooking without extraction", value: "Cooking without extraction" },
            { label: "Showering without extraction", value: "Showering without extraction" },
            { label: "Drying clothes indoors", value: "Drying clothes indoors" },
            { label: "Many houseplants", value: "Many houseplants" },
            { label: "Fish tanks / humidifiers", value: "Fish tanks / humidifiers" },
            { label: "Low occupancy / minimal sources", value: "Low occupancy / minimal sources" },
          ],
        },
        {
          kind: "chips",
          key: "occupancy",
          label: "Hours at home / occupancy pattern",
          mode: "single",
          options: [
            { label: "All day (high exposure)", value: "All day (high exposure)" },
            { label: "Most of day", value: "Most of day" },
            { label: "Evenings/weekends only", value: "Evenings/weekends only" },
            { label: "Mostly unoccupied", value: "Mostly unoccupied" },
          ],
        },
        {
          kind: "chips",
          key: "dewPointRisk",
          label: "Dew point / condensation risk level",
          mode: "single",
          options: [
            { label: "Low risk (<55% RH, warm surfaces)", value: "Low risk (<55% RH, warm surfaces)" },
            { label: "Moderate risk (55–65% RH)", value: "Moderate risk (55–65% RH)" },
            { label: "High risk (>65% RH, cold surfaces)", value: "High risk (>65% RH, cold surfaces)" },
            { label: "Not assessed", value: "Not assessed" },
          ],
        },
        {
          kind: "textarea",
          key: "ventNotes",
          label: "Ventilation/environment notes",
          placeholder:
            "Note any air leakage points, window habits, heating patterns, or other relevant lifestyle factors...",
        },
      ],
    },
    {
      id: 7,
      title: "Types of Damp & Moisture Sources",
      desc: "Identify the probable type(s) of damp and their root causes.",
      questions: [
        {
          kind: "chips",
          key: "dampTypes",
          label: "Primary damp type(s) identified",
          mode: "multi",
          options: [
            { label: "Condensation", value: "Condensation (poor ventilation)" },
            { label: "Rising damp", value: "Rising damp / capillary action" },
            { label: "Penetrating damp", value: "Penetrating damp (rain ingress)" },
            { label: "Plumbing leak", value: "Plumbing leak" },
            { label: "Construction moisture", value: "Construction moisture" },
            { label: "Hygroscopic salts", value: "Hygroscopic / deliquescent salts" },
            { label: "Interstitial condensation", value: "Interstitial condensation" },
            { label: "Flood damage", value: "Flood / post-water damage" },
          ],
        },
        {
          kind: "chips",
          key: "diagnosisConfidence",
          label: "Confidence in diagnosis",
          mode: "single",
          options: [
            { label: "High – clear evidence", value: "High – clear evidence" },
            { label: "Medium – probable", value: "Medium – probable" },
            { label: "Low – uncertain, needs further investigation", value: "Low – uncertain, needs further investigation" },
          ],
        },
        {
          kind: "chips",
          key: "risingDampIndicators",
          label: "Rising damp indicators (if applicable)",
          mode: "multi",
          options: [
            { label: "Tide marks on lower walls", value: "Tide marks on lower walls" },
            { label: "Salt deposits at low level", value: "Salt deposits at low level" },
            { label: "Moisture tapers from base upward", value: "Moisture tapers from base upward" },
            { label: "DPC absent/failed", value: "DPC absent/failed" },
            { label: "N/A", value: "N/A" },
          ],
        },
        {
          kind: "chips",
          key: "penetratingIndicators",
          label: "Penetrating damp indicators (if applicable)",
          mode: "multi",
          options: [
            { label: "Damp at window reveals", value: "Damp at window reveals" },
            { label: "Damp below roof line", value: "Damp below roof line" },
            { label: "Localised patch after rain", value: "Localised patch after rain" },
            { label: "Damp at chimney breast", value: "Damp at chimney breast" },
            { label: "N/A", value: "N/A" },
          ],
        },
        {
          kind: "textarea",
          key: "dampDiagNotes",
          label: "Additional diagnostic notes",
          placeholder:
            "Describe the logic behind your diagnosis, any conflicting signs, or tests performed to differentiate types...",
        },
      ],
    },
    {
      id: 8,
      title: "Timber & Material Defects",
      desc: "Assess condition of timber elements, insulation and floor coverings.",
      questions: [
        {
          kind: "chips",
          key: "timberCondition",
          label: "Timber condition (skirtings, joists, floorboards)",
          mode: "multi",
          options: [
            { label: "Sound – no defects", value: "Sound – no defects" },
            { label: "Surface staining only", value: "Surface staining only" },
            { label: "Wet rot present", value: "Wet rot present" },
            { label: "Dry rot present", value: "Dry rot present" },
            { label: "Fungal strands observed", value: "Fungal strands observed" },
            { label: "Structural compromise", value: "Structural compromise" },
          ],
        },
        {
          kind: "chips",
          key: "insects",
          label: "Insect infestation",
          mode: "single",
          options: [
            { label: "None", value: "None" },
            { label: "Active woodworm", value: "Active woodworm" },
            { label: "Inactive woodworm", value: "Inactive woodworm" },
            { label: "Termites", value: "Termites" },
            { label: "Other", value: "Other" },
          ],
        },
        {
          kind: "chips",
          key: "insulationCondition",
          label: "Insulation condition",
          mode: "single",
          options: [
            { label: "Good – dry and intact", value: "Good – dry and intact" },
            { label: "Wet / saturated", value: "Wet / saturated" },
            { label: "Compressed and degraded", value: "Compressed and degraded" },
            { label: "Mouldy", value: "Mouldy" },
            { label: "Not present / N/A", value: "Not present / N/A" },
          ],
        },
        {
          kind: "chips",
          key: "floorCoverings",
          label: "Floor coverings condition",
          mode: "multi",
          options: [
            { label: "Dry and sound", value: "Dry and sound" },
            { label: "Damp under carpet", value: "Damp under carpet" },
            { label: "Damp under vinyl/laminate", value: "Damp under vinyl/laminate" },
            { label: "Underlay saturated", value: "Underlay saturated" },
            { label: "Lifting / bubbling", value: "Lifting / bubbling" },
          ],
        },
        {
          kind: "chips",
          key: "timberMC",
          label: "Timber MC% readings",
          mode: "single",
          options: [
            { label: "Dry (<18%)", value: "Dry (<18%)" },
            { label: "Slightly elevated (18–20%)", value: "Slightly elevated (18–20%)" },
            { label: "At risk (20–25%)", value: "At risk (20–25%)" },
            { label: "Wet rot risk (>25%)", value: "Wet rot risk (>25%)" },
            { label: "Not measured", value: "Not measured" },
          ],
        },
        {
          kind: "textarea",
          key: "timberNotes",
          label: "Timber/material notes",
          placeholder:
            "Note locations, extent of decay, which elements affected, any fruiting bodies, smell of dry rot...",
        },
      ],
    },
    {
      id: 9,
      title: "Structural & Building Defects",
      desc: "Record cracks, structural anomalies and other building defects.",
      questions: [
        {
          kind: "chips",
          key: "cracks",
          label: "Cracks observed",
          mode: "multi",
          options: [
            { label: "No cracks", value: "No cracks" },
            { label: "Hairline cracks – cosmetic", value: "Hairline cracks – cosmetic" },
            { label: "Diagonal cracks – settlement", value: "Diagonal cracks – settlement" },
            { label: "Horizontal cracks – structural concern", value: "Horizontal cracks – structural concern" },
            { label: "Vertical cracks", value: "Vertical cracks" },
            { label: "Active (widening)", value: "Active (widening)" },
            { label: "Historic (stable)", value: "Historic (stable)" },
          ],
        },
        {
          kind: "chips",
          key: "crackWidth",
          label: "Crack width",
          mode: "single",
          options: [
            { label: "<1mm (fine)", value: "<1mm (fine)" },
            { label: "1–5mm (moderate)", value: "1–5mm (moderate)" },
            { label: "5–15mm (wide – concern)", value: "5–15mm (wide – concern)" },
            { label: ">15mm (severe)", value: ">15mm (severe)" },
            { label: "N/A – no cracks", value: "N/A – no cracks" },
          ],
        },
        {
          kind: "chips",
          key: "subsidence",
          label: "Subsidence / settlement signs",
          mode: "single",
          options: [
            { label: "None observed", value: "None observed" },
            { label: "Minor – monitoring advised", value: "Minor – monitoring advised" },
            { label: "Suspected – investigation needed", value: "Suspected – investigation needed" },
            { label: "Active subsidence", value: "Active subsidence" },
          ],
        },
        {
          kind: "chips",
          key: "chimneyDefects",
          label: "Chimney / fireplace defects",
          mode: "multi",
          options: [
            { label: "No defects / N/A", value: "No defects / N/A" },
            { label: "Damp at chimney breast", value: "Damp at chimney breast" },
            { label: "Salt deposits at breast", value: "Salt deposits at breast" },
            { label: "Capping absent", value: "Capping absent" },
            { label: "Failed flashing", value: "Failed flashing" },
          ],
        },
        {
          kind: "chips",
          key: "otherStructural",
          label: "Other structural concerns",
          mode: "multi",
          options: [
            { label: "None", value: "None" },
            { label: "Blocked cavity wall", value: "Blocked cavity wall" },
            { label: "Wall tie failure suspected", value: "Wall tie failure suspected" },
            { label: "Service penetrations (unsealed)", value: "Service penetrations (unsealed)" },
            { label: "Foundation damp-proofing visible failure", value: "Foundation damp-proofing visible failure" },
          ],
        },
        {
          kind: "textarea",
          key: "structuralNotes",
          label: "Structural notes",
          placeholder:
            "Describe crack patterns, locations, any structural engineer involvement or concerns...",
        },
      ],
    },
    {
      id: 10,
      title: "History & Previous Interventions",
      desc: "Document prior treatments, repairs, and moisture events.",
      questions: [
        {
          kind: "chips",
          key: "prevTreatments",
          label: "Previous damp treatments",
          mode: "multi",
          options: [
            { label: "No previous treatments", value: "No previous treatments" },
            { label: "Chemical DPC injection", value: "Chemical DPC injection" },
            { label: "Membranes / tanking", value: "Waterproof membranes / tanking" },
            { label: "Waterproof renders", value: "Waterproof renders applied" },
            { label: "Timber treatment", value: "Timber treatment (fungicide)" },
            { label: "Drainage / sump", value: "Drainage / sump installed" },
          ],
        },
        {
          kind: "chips",
          key: "priorSurvey",
          label: "Prior survey / guarantee",
          mode: "single",
          options: [
            { label: "Yes – recent (within 5 years)", value: "Yes – recent (within 5 years)" },
            { label: "Yes – older", value: "Yes – older" },
            { label: "Guarantee in place", value: "Guarantee in place" },
            { label: "No prior survey", value: "No prior survey" },
          ],
        },
        {
          kind: "chips",
          key: "mouldRemediation",
          label: "Previous mould remediation",
          mode: "multi",
          options: [
            { label: "None", value: "None" },
            { label: "Surface cleaning", value: "Surface cleaning performed" },
            { label: "Dry fogging", value: "Dry fogging / antimicrobial" },
            { label: "Ventilation upgrade", value: "Ventilation upgrade" },
            { label: "Material removal", value: "Material removal" },
          ],
        },
        {
          kind: "chips",
          key: "maintenance",
          label: "Maintenance history",
          mode: "multi",
          options: [
            { label: "Regular maintenance", value: "Regular maintenance" },
            { label: "Roof repairs done", value: "Roof repairs done" },
            { label: "Gutter cleaning done", value: "Gutter cleaning done" },
            { label: "Re-rendering done", value: "Re-rendering done" },
            { label: "Plumbing fixes done", value: "Plumbing fixes done" },
            { label: "No maintenance", value: "No maintenance" },
          ],
        },
        {
          kind: "textarea",
          key: "historyNotes",
          label: "History notes",
          placeholder:
            "Dates of previous works, names of contractors, outcomes of prior treatments, dates of flood events...",
        },
      ],
    },
    {
      id: 11,
      title: "Risk Assessment & Impacts",
      desc: "Evaluate severity, health risks, structural impacts and urgency.",
      questions: [
        {
          kind: "chips",
          key: "severity",
          label: "Overall severity rating",
          mode: "single",
          options: [
            { label: "🟢 Low", value: "Low", className: "sev-low" },
            { label: "🟡 Medium", value: "Medium", className: "sev-med" },
            { label: "🟠 High", value: "High", className: "sev-high" },
            { label: "🔴 Severe", value: "Severe", className: "sev-sev" },
          ],
        },
        {
          kind: "chips",
          key: "extentAffected",
          label: "Estimated extent of affected surfaces",
          mode: "single",
          options: [
            { label: "<5m² (minor)", value: "<5m² (minor)" },
            { label: "5–20m² (moderate)", value: "5–20m² (moderate)" },
            { label: "20–50m² (significant)", value: "20–50m² (significant)" },
            { label: ">50m² (extensive)", value: ">50m² (extensive)" },
          ],
        },
        {
          kind: "chips",
          key: "healthRisks",
          label: "Health & safety risks identified",
          mode: "multi",
          options: [
            { label: "Mould spore exposure", value: "Mould spore exposure" },
            { label: "Respiratory risk", value: "Respiratory risk" },
            { label: "Allergic / asthma risk", value: "Allergic reactions / asthma" },
            { label: "Dust mites", value: "Dust mites (elevated humidity)" },
            { label: "VOCs from mould", value: "VOCs from mould" },
            { label: "Slip risk (wet floors)", value: "Slip risk (wet floors)" },
            { label: "Minimal health risk", value: "Minimal health risk" },
          ],
        },
        {
          kind: "chips",
          key: "vulnerable",
          label: "Vulnerable occupants present?",
          mode: "multi",
          options: [
            { label: "Children", value: "Children" },
            { label: "Elderly", value: "Elderly" },
            { label: "Asthma / respiratory", value: "Asthma / respiratory conditions" },
            { label: "Immunocompromised", value: "Immunocompromised" },
            { label: "None / unknown", value: "None / unknown" },
          ],
        },
        {
          kind: "chips",
          key: "structuralRisk",
          label: "Structural risk level",
          mode: "single",
          options: [
            { label: "No structural risk", value: "No structural risk" },
            { label: "Timber weakening risk", value: "Timber weakening risk" },
            { label: "Material degradation ongoing", value: "Material degradation ongoing" },
            { label: "Active structural concern", value: "Active structural concern" },
          ],
        },
        {
          kind: "chips",
          key: "urgency",
          label: "Urgency of action",
          mode: "single",
          options: [
            { label: "Monitor only", value: "Monitor only" },
            { label: "Within 3–6 months", value: "Within 3–6 months" },
            { label: "Within 1 month", value: "Within 1 month" },
            { label: "Immediate action required", value: "Immediate action required" },
          ],
        },
      ],
    },
    {
      id: 12,
      title: "Inspections & Methods Used",
      desc: "Record the inspection methods, equipment and verification approaches used.",
      questions: [
        {
          kind: "chips",
          key: "inspectionMethods",
          label: "Inspection methods performed",
          mode: "multi",
          options: [
            { label: "Visual inspection", value: "Visual inspection" },
            { label: "Moisture profiling (pin)", value: "Moisture profiling (pin meter)" },
            { label: "Moisture profiling (non-invasive)", value: "Moisture profiling (non-invasive)" },
            { label: "Thermal imaging", value: "Thermal imaging / IR camera" },
            { label: "Hygrometer / dew point", value: "Hygrometer / dew point assessment" },
            { label: "Salt analysis", value: "Salt / hygroscopic analysis" },
            { label: "Laboratory testing", value: "Laboratory testing" },
            { label: "Borescope / endoscope", value: "Borescope / endoscope" },
            { label: "Airborne spore sampling", value: "Airborne spore sampling" },
            { label: "Photographic log", value: "Photographic evidence log" },
            { label: "Client remote intake", value: "Client remote intake (photos/video)" },
          ],
        },
        {
          kind: "chips",
          key: "dpcInspection",
          label: "DPC / damp-proof membrane inspection",
          mode: "single",
          options: [
            { label: "Inspected – adequate", value: "Inspected – adequate" },
            { label: "Inspected – defective", value: "Inspected – defective" },
            { label: "Inspected – absent", value: "Inspected – absent" },
            { label: "Not accessible", value: "Not accessible / not inspected" },
          ],
        },
        {
          kind: "chips",
          key: "evidenceQuality",
          label: "Photographic / video evidence quality",
          mode: "single",
          options: [
            { label: "Comprehensive", value: "Comprehensive – all areas documented" },
            { label: "Partial", value: "Partial – some areas" },
            { label: "Minimal", value: "Minimal – key areas only" },
            { label: "None", value: "None" },
          ],
        },
        {
          kind: "textarea",
          key: "inspectionNotes",
          label: "Inspection method notes",
          placeholder:
            "List specific equipment used (make/model), any access limitations, areas not inspected and reasons...",
        },
      ],
    },
    {
      id: 13,
      title: "Safety, Recommendations & Remediation",
      desc: "Define the remediation plan, treatments and long-term prevention strategy.",
      questions: [
        {
          kind: "chips",
          key: "remediationActions",
          label: "Recommended remediation actions",
          mode: "multi",
          options: [
            { label: "Ventilation upgrade", value: "Ventilation upgrade (mechanical)" },
            { label: "Dehumidifier", value: "Dehumidifier / humidity control" },
            { label: "DPC chemical injection", value: "DPC chemical injection" },
            { label: "New DPC membrane", value: "New DPC membrane" },
            { label: "Re-pointing / render", value: "Re-pointing / render replacement" },
            { label: "External waterproofing", value: "External waterproofing" },
            { label: "Window / door seals", value: "Window / door seal replacement" },
            { label: "Timber treatment", value: "Timber treatment / replacement" },
            { label: "Drainage / gutters", value: "Drainage / gutter improvements" },
            { label: "Ground level adjustment", value: "Ground level adjustment" },
            { label: "Insulation upgrade", value: "Insulation upgrade (breathable)" },
            { label: "Dry fogging", value: "Dry fogging / antimicrobial treatment" },
            { label: "Material removal", value: "Material removal (drywall / insulation)" },
          ],
        },
        {
          kind: "chips",
          key: "costBand",
          label: "Estimated cost band",
          mode: "single",
          options: [
            { label: "Low (<€1,000)", value: "Low (<€1,000)" },
            { label: "Medium (€1,000–€5,000)", value: "Medium (€1,000–€5,000)" },
            { label: "High (€5,000–€15,000)", value: "High (€5,000–€15,000)" },
            { label: "Very high (>€15,000)", value: "Very high (>€15,000)" },
          ],
        },
        {
          kind: "chips",
          key: "specialists",
          label: "Specialist referrals needed",
          mode: "multi",
          options: [
            { label: "None required", value: "None required" },
            { label: "Structural engineer", value: "Structural engineer" },
            { label: "Waterproofing specialist", value: "Waterproofing specialist" },
            { label: "Timber specialist", value: "Timber / dry rot specialist" },
            { label: "Plumber", value: "Plumber" },
            { label: "Building surveyor", value: "Building surveyor" },
            { label: "Environmental health", value: "Environmental health" },
          ],
        },
        {
          kind: "chips",
          key: "prevention",
          label: "Long-term prevention measures",
          mode: "multi",
          options: [
            { label: "Annual monitoring plan", value: "Annual monitoring plan" },
            { label: "Breathable materials", value: "Breathable materials only" },
            { label: "Lifestyle advice", value: "Lifestyle advice to occupant" },
            { label: "Regular maintenance", value: "Regular gutter/roof maintenance" },
            { label: "Hygrometer installation", value: "Hygrometer installation" },
            { label: "Building fabric upgrade", value: "Building fabric upgrade" },
          ],
        },
        {
          kind: "textarea",
          key: "finalNotes",
          label: "Surveyor's final notes & observations",
          placeholder:
            "Any additional context, client communication notes, priority actions, or caveats to include in the report...",
        },
      ],
    },
  ],
  pt: [
    {
      id: 1,
      title: "Informações básicas do edifício",
      desc: "Comece com detalhes fundamentais sobre o imóvel a avaliar.",
      questions: [
        {
          kind: "chips",
          key: "buildingType",
          label: "Tipo de edifício",
          required: true,
          mode: "single",
          options: [
            { label: "Apartamento", value: "Apartment" },
            { label: "Moradia", value: "House" },
            { label: "Comercial", value: "Commercial" },
            { label: "Cave / Garagem", value: "Basement/Garage" },
            { label: "Outro", value: "Other" },
          ],
        },
        {
          kind: "chips",
          key: "constructionType",
          label: "Tipo de construção",
          mode: "multi",
          options: [
            { label: "Betão", value: "Concrete" },
            { label: "Tijolo", value: "Brick" },
            { label: "Pedra", value: "Stone" },
            { label: "Estrutura de madeira", value: "Timber frame" },
            { label: "Parede maciça", value: "Solid wall" },
            { label: "Parede dupla (caixa de ar)", value: "Cavity wall" },
            { label: "Mista", value: "Mixed" },
          ],
        },
        {
          kind: "chips",
          key: "ownership",
          label: "Tipo de ocupação / titularidade",
          mode: "single",
          options: [
            { label: "Proprietário", value: "Owner" },
            { label: "Inquilino", value: "Tenant" },
            { label: "Imóvel arrendado", value: "Rental property" },
            { label: "Habitação social", value: "Social housing" },
          ],
        },
        {
          kind: "inputs",
          fields: [
            {
              key: "yearBuilt",
              label: "Ano de construção",
              type: "number",
              placeholder: "ex.: 1978",
            },
            {
              key: "buildingArea",
              label: "Área do edifício (m²)",
              type: "number",
              placeholder: "ex.: 120",
            },
            {
              key: "floorsAffected",
              label: "N.º de pisos afetados",
              type: "number",
              placeholder: "ex.: 2",
            },
            {
              key: "location",
              label: "Morada / Localização",
              type: "text",
              placeholder: "Cidade ou zona",
            },
          ],
        },
        {
          kind: "chips",
          key: "floodRisk",
          label: "Cota / risco de inundação",
          mode: "single",
          options: [
            { label: "Baixo risco", value: "Low risk" },
            { label: "Risco médio", value: "Medium risk" },
            { label: "Elevado / zona inundável", value: "High / flood zone" },
            { label: "Desconhecido", value: "Unknown" },
          ],
        },
      ],
    },
    {
      id: 2,
      title: "Características do edifício",
      desc: "Elementos estruturais e materiais relevantes para a humidade.",
      questions: [
        {
          kind: "chips",
          key: "wallMaterials",
          label: "Materiais das paredes",
          mode: "multi",
          options: [
            { label: "Tijolo", value: "Brick" },
            { label: "Pedra", value: "Stone" },
            { label: "Bloco de betão", value: "Concrete block" },
            { label: "Reboco areia/cimento", value: "Sand/cement render" },
            { label: "Reboco de cal", value: "Lime render" },
            { label: "Alvenaria porosa", value: "Porous masonry" },
            { label: "Revestimento não poroso", value: "Non-porous cladding" },
          ],
        },
        {
          kind: "chips",
          key: "dpcPresent",
          label: "Existe DPC (barreira anti-humidade)?",
          mode: "single",
          options: [
            { label: "Sim – DPC físico", value: "Yes – physical DPC" },
            { label: "Sim – injeção química", value: "Yes – chemical injection" },
            { label: "Sem DPC", value: "No DPC" },
            { label: "Desconhecido", value: "Unknown" },
          ],
        },
        {
          kind: "chips",
          key: "dpcCondition",
          label: "Estado do DPC",
          mode: "single",
          options: [
            { label: "Íntegro / funcional", value: "Intact / functioning" },
            { label: "Ponte / bypass", value: "Bridged or bypassed" },
            { label: "Falhado / degradado", value: "Failed / degraded" },
            { label: "Não é possível determinar", value: "Cannot determine" },
          ],
        },
        {
          kind: "chips",
          key: "floorType",
          label: "Tipo de pavimento (construção)",
          mode: "single",
          options: [
            { label: "Laje maciça de betão", value: "Solid concrete slab" },
            { label: "Estrutura suspensa de madeira", value: "Suspended timber" },
            { label: "Vigas e blocos", value: "Beam & block" },
            { label: "Misto", value: "Mixed" },
          ],
        },
        {
          kind: "chips",
          key: "roofType",
          label: "Cobertura (tipo)",
          mode: "multi",
          options: [
            { label: "Inclinada – telha", value: "Pitched – tiles" },
            { label: "Inclinada – ardósia", value: "Pitched – slate" },
            { label: "Plana – membrana", value: "Flat roof membrane" },
            { label: "EPDM / felt (plana)", value: "EPDM / felt flat" },
            { label: "Cobertura verde", value: "Green roof" },
          ],
        },
        {
          kind: "chips",
          key: "glazing",
          label: "Tipo de envidraçado",
          mode: "single",
          options: [
            { label: "Vidro simples", value: "Single glazed" },
            { label: "Vidro duplo", value: "Double glazed" },
            { label: "Vidro triplo", value: "Triple glazed" },
            { label: "Misto", value: "Mixed" },
          ],
        },
        {
          kind: "chips",
          key: "groundLevel",
          label: "Cota exterior vs pavimento interior",
          mode: "single",
          options: [
            { label: "Exterior mais baixo (normal)", value: "External lower (normal)" },
            { label: "Exterior ao mesmo nível", value: "External at same level" },
            { label: "Exterior mais alto (risco de ponte)", value: "External higher (bridging risk)" },
          ],
        },
        {
          kind: "chips",
          key: "subfloorVent",
          label: "Ventilação sob o pavimento",
          mode: "single",
          options: [
            { label: "Grelhas adequadas – desobstruídas", value: "Adequate grilles – clear" },
            { label: "Grelhas presentes – obstruídas", value: "Grilles present – blocked" },
            { label: "Sem grelhas / respiros", value: "No grilles / vents" },
            { label: "N/A (pavimento maciço)", value: "N/A (solid floor)" },
          ],
        },
        {
          kind: "chips",
          key: "wallThickness",
          label: "Espessura da parede",
          mode: "single",
          options: [
            { label: "<200mm (fina)", value: "<200mm (thin)" },
            { label: "200–300mm", value: "200–300mm" },
            { label: "300–500mm (maciça)", value: "300–500mm (solid)" },
            { label: ">500mm (pedra espessa)", value: ">500mm (thick stone)" },
          ],
        },
      ],
    },
    {
      id: 3,
      title: "Pontos de entrada de humidade (exterior)",
      desc: "Identifique defeitos exteriores que possam permitir a entrada de água no edifício.",
      questions: [
        {
          kind: "chips",
          key: "roofCondition",
          label: "Estado da cobertura",
          mode: "multi",
          options: [
            { label: "Bom – sem defeitos", value: "Good – no defects" },
            { label: "Telhas em falta/partidas", value: "Missing/broken tiles" },
            { label: "Rufos/flashings defeituosos", value: "Defective flashings" },
            { label: "Rejuntamento da chaminé falhado", value: "Chimney pointing failed" },
            { label: "Defeitos em caleiras/vales", value: "Valley defects" },
            { label: "Fuga ativa confirmada", value: "Active leak confirmed" },
          ],
        },
        {
          kind: "chips",
          key: "gutters",
          label: "Caleiras e tubos de queda",
          mode: "multi",
          options: [
            { label: "Desimpedidas e funcionais", value: "Clear and functioning" },
            { label: "Caleiras obstruídas", value: "Blocked gutters" },
            { label: "Juntas com fugas", value: "Leaking joints" },
            { label: "A transbordar", value: "Overflowing" },
            { label: "Descarga junto à parede", value: "Downpipe discharging near wall" },
            { label: "Secções em falta", value: "Missing sections" },
          ],
        },
        {
          kind: "chips",
          key: "externalWallDefects",
          label: "Defeitos nas paredes exteriores",
          mode: "multi",
          options: [
            { label: "Sem defeitos", value: "No defects" },
            { label: "Rejuntamento falhado", value: "Failed pointing" },
            { label: "Fissuras no reboco", value: "Render cracks" },
            { label: "Desagregação da alvenaria", value: "Masonry spalling" },
            { label: "Sem impermeabilização", value: "No waterproofing" },
            { label: "Fissura ao nível do DPC", value: "Crack at DPC level" },
          ],
        },
        {
          kind: "chips",
          key: "windowDefects",
          label: "Encontros de janelas e portas",
          mode: "multi",
          options: [
            { label: "Tudo selado – bom", value: "All sealed – good" },
            { label: "Selagens/vidrilhos falhados", value: "Failed seals/beading" },
            { label: "Peitoril/goteira em falta", value: "Missing sill or drip" },
            { label: "Lintéis fissurados", value: "Cracked lintels" },
            { label: "Rufos defeituosos no topo", value: "Defective flashing at head" },
          ],
        },
        {
          kind: "chips",
          key: "drainage",
          label: "Arranjos exteriores e drenagem",
          mode: "multi",
          options: [
            { label: "Terreno inclina para fora – bom", value: "Ground slopes away – good" },
            { label: "Terreno inclina para o edifício", value: "Ground slopes toward building" },
            { label: "Água estagnada observada", value: "Standing water observed" },
            { label: "Pavimento exterior causa ponte", value: "Paved area causing bridging" },
            { label: "Solo acima do DPC", value: "Soil raised above DPC" },
          ],
        },
        {
          kind: "chips",
          key: "externalPlumbing",
          label: "Problemas de canalização exterior",
          mode: "multi",
          options: [
            { label: "Sem problemas", value: "No issues" },
            { label: "Histórico de rotura de tubo", value: "Known pipe burst history" },
            { label: "Fuga suspeita", value: "Suspected leak" },
            { label: "Falha na drenagem", value: "Drainage failure" },
          ],
        },
        {
          kind: "textarea",
          key: "externalNotes",
          label: "Notas adicionais sobre defeitos exteriores",
          placeholder:
            "Descreva observações exteriores específicas, localizações, gravidade...",
        },
      ],
    },
    {
      id: 4,
      title: "Sinais internos de humidade e bolor",
      desc: "Registe evidência interna visível de problemas de humidade.",
      questions: [
        {
          kind: "chips",
          key: "visibleSigns",
          label: "Sinais visíveis presentes",
          mode: "multi",
          options: [
            { label: "Marcas de maré / manchas", value: "Tide marks / staining" },
            { label: "Bolor preto", value: "Black mould" },
            { label: "Bolor verde/branco", value: "Green/white mould" },
            { label: "Tinta/reboco a descascar", value: "Peeling paint/plaster" },
            { label: "Eflorescências (sais)", value: "Efflorescence (salt deposits)" },
            { label: "Odor a mofo", value: "Musty odour" },
            { label: "Sem sinais visíveis", value: "No visible signs" },
          ],
        },
        {
          kind: "chips",
          key: "locations",
          label: "Localizações / divisões afetadas",
          mode: "multi",
          options: [
            { label: "Paredes do rés-do-chão – base", value: "Ground floor walls – base" },
            { label: "Zonas superiores das paredes", value: "Upper wall areas" },
            { label: "Teto", value: "Ceiling" },
            { label: "Superfície do pavimento", value: "Floor surface" },
            { label: "Rodapés", value: "Skirtings" },
            { label: "Cantos", value: "Corners" },
            { label: "Atrás de mobiliário", value: "Behind furniture" },
            { label: "Casa de banho/cozinha", value: "Bathroom/kitchen" },
            { label: "Cave/adega", value: "Basement/cellar" },
          ],
        },
        {
          kind: "chips",
          key: "condensation",
          label: "Evidência de condensação",
          mode: "multi",
          options: [
            { label: "Não observada", value: "None observed" },
            { label: "Em janelas", value: "On windows" },
            { label: "Em tubos frios", value: "On cold pipes" },
            { label: "Em superfícies frias de paredes", value: "On cold wall surfaces" },
            { label: "Em tetos", value: "On ceilings" },
          ],
        },
        {
          kind: "chips",
          key: "timberDecay",
          label: "Degradação de madeira / atividade de insetos",
          mode: "multi",
          options: [
            { label: "Nenhuma", value: "None" },
            { label: "Podridão húmida", value: "Wet rot" },
            { label: "Podridão seca", value: "Dry rot" },
            { label: "Crescimento fúngico", value: "Fungal growth" },
            { label: "Caruncho ativo", value: "Active woodworm" },
            { label: "Caruncho inativo", value: "Inactive woodworm" },
          ],
        },
        {
          kind: "chips",
          key: "floodHistory",
          label: "Histórico de inundações/água acumulada no interior",
          mode: "single",
          options: [
            { label: "Sem histórico", value: "No history" },
            { label: "Evento único", value: "Single event" },
            { label: "Eventos recorrentes", value: "Recurring events" },
            { label: "Atualmente afetado", value: "Currently affected" },
          ],
        },
        {
          kind: "textarea",
          key: "internalNotes",
          label: "Observações internas / notas",
          placeholder:
            "Detalhe divisões/localizações, alturas dos danos, cores do bolor, área aproximada afetada (m²)...",
        },
      ],
    },
    {
      id: 5,
      title: "Medições e perfilagem de humidade",
      desc: "Registe leituras instrumentais e dados de humidade do levantamento.",
      questions: [
        {
          kind: "chips",
          key: "meterType",
          label: "Tipo de medidor de humidade utilizado",
          mode: "multi",
          options: [
            { label: "Medidor de pinos", value: "Pin meter" },
            { label: "Não invasivo / RF", value: "Non-invasive / RF meter" },
            { label: "Ambos", value: "Both" },
            { label: "Não utilizado", value: "Not used" },
          ],
        },
        {
          kind: "chips",
          key: "mcBase",
          label: "Teor de humidade (MC%) na base da parede",
          mode: "single",
          options: [
            { label: "Seco (<10%)", value: "Dry (<10%)" },
            { label: "Ligeiramente húmido (10–15%)", value: "Slightly damp (10–15%)" },
            { label: "Húmido (15–20%)", value: "Damp (15–20%)" },
            { label: "Muito húmido (>20%)", value: "Very wet (>20%)" },
            { label: "Não medido", value: "Not measured" },
          ],
        },
        {
          kind: "chips",
          key: "moistureHeight",
          label: "Perfil de altura da subida de humidade",
          mode: "single",
          options: [
            { label: "<300mm (muito baixo)", value: "<300mm (very low)" },
            { label: "300–600mm", value: "300–600mm" },
            { label: "600mm–1m", value: "600mm–1m" },
            { label: ">1m (subida elevada)", value: ">1m (high rise)" },
            { label: "Uniforme (não é ascendente)", value: "Uniform (not rising damp)" },
            { label: "Não medido", value: "Not measured" },
          ],
        },
        {
          kind: "chips",
          key: "rh",
          label: "Humidade relativa (%RH) medida",
          mode: "single",
          options: [
            { label: "Abaixo de 60% – aceitável", value: "Below 60% – acceptable" },
            { label: "60–70% – elevada", value: "60–70% – elevated" },
            { label: "70–80% – alta", value: "70–80% – high" },
            { label: ">80% – muito alta", value: ">80% – very high" },
            { label: "Não medido", value: "Not measured" },
          ],
        },
        {
          kind: "chips",
          key: "thermal",
          label: "Termografia / infravermelhos",
          mode: "single",
          options: [
            { label: "Realizada – sem anomalias", value: "Performed – no anomalies" },
            { label: "Realizada – pontes térmicas", value: "Performed – cold bridges found" },
            { label: "Realizada – humidade oculta", value: "Performed – hidden moisture found" },
            { label: "Não realizada", value: "Not performed" },
          ],
        },
        {
          kind: "chips",
          key: "saltTest",
          label: "Análise higroscópica/sais realizada?",
          mode: "single",
          options: [
            { label: "Sim – negativa (sem sais relevantes)", value: "Yes – negative (no significant salts)" },
            { label: "Sim – positiva (nitratos detetados)", value: "Yes – positive (nitrates detected)" },
            { label: "Sim – positiva (cloretos detetados)", value: "Yes – positive (chlorides detected)" },
            { label: "Sim – níveis altos (laboratório)", value: "Yes – high levels (lab confirmed)" },
            { label: "Não realizada", value: "Not performed" },
          ],
        },
        {
          kind: "textarea",
          key: "measurementNotes",
          label: "Notas e leituras de medição",
          placeholder:
            "Registe leituras específicas, localizações, ponto de orvalho, temperaturas de superfície, descrição do mapeamento...",
        },
      ],
    },
    {
      id: 6,
      title: "Ventilação, humidade e ambiente",
      desc: "Avalie sistemas de ventilação e condições ambientais no edifício.",
      questions: [
        {
          kind: "chips",
          key: "ventType",
          label: "Tipo de ventilação presente",
          mode: "multi",
          options: [
            { label: "Natural – janelas abríveis", value: "Natural – openable windows" },
            { label: "Extratores mecânicos", value: "Mechanical extractor fans" },
            { label: "Entradas de ar nas caixilharias", value: "Trickle vents in frames" },
            { label: "Tijolos de ventilação", value: "Subfloor air bricks" },
            { label: "MVHR (recuperação de calor)", value: "MVHR (heat recovery)" },
            { label: "PIV (insuflação positiva)", value: "PIV (positive input)" },
            { label: "Sem ventilação", value: "No ventilation" },
          ],
        },
        {
          kind: "chips",
          key: "ventEffectiveness",
          label: "Eficácia da ventilação",
          mode: "single",
          options: [
            { label: "Adequada", value: "Adequate" },
            { label: "Parcialmente adequada", value: "Partially adequate" },
            { label: "Inadequada", value: "Inadequate" },
            { label: "Muito fraca / inexistente", value: "Very poor / none" },
          ],
        },
        {
          kind: "chips",
          key: "humidSources",
          label: "Fontes internas de humidade",
          mode: "multi",
          options: [
            { label: "Alta ocupação", value: "High occupancy" },
            { label: "Cozinhar sem extração", value: "Cooking without extraction" },
            { label: "Banhos sem extração", value: "Showering without extraction" },
            { label: "Secar roupa no interior", value: "Drying clothes indoors" },
            { label: "Muitas plantas", value: "Many houseplants" },
            { label: "Aquários / humidificadores", value: "Fish tanks / humidifiers" },
            { label: "Baixa ocupação / fontes mínimas", value: "Low occupancy / minimal sources" },
          ],
        },
        {
          kind: "chips",
          key: "occupancy",
          label: "Horas em casa / padrão de ocupação",
          mode: "single",
          options: [
            { label: "Todo o dia (alta exposição)", value: "All day (high exposure)" },
            { label: "Maior parte do dia", value: "Most of day" },
            { label: "Só noites/fins-de-semana", value: "Evenings/weekends only" },
            { label: "Maioritariamente desocupado", value: "Mostly unoccupied" },
          ],
        },
        {
          kind: "chips",
          key: "dewPointRisk",
          label: "Risco (ponto de orvalho / condensação)",
          mode: "single",
          options: [
            { label: "Baixo (<55% RH, superfícies quentes)", value: "Low risk (<55% RH, warm surfaces)" },
            { label: "Moderado (55–65% RH)", value: "Moderate risk (55–65% RH)" },
            { label: "Alto (>65% RH, superfícies frias)", value: "High risk (>65% RH, cold surfaces)" },
            { label: "Não avaliado", value: "Not assessed" },
          ],
        },
        {
          kind: "textarea",
          key: "ventNotes",
          label: "Notas de ventilação/ambiente",
          placeholder:
            "Registe infiltrações de ar, hábitos de janelas, padrões de aquecimento, ou outros fatores relevantes...",
        },
      ],
    },
    {
      id: 7,
      title: "Tipos de humidade e fontes prováveis",
      desc: "Identifique o(s) tipo(s) provável(is) de humidade e as causas raiz.",
      questions: [
        {
          kind: "chips",
          key: "dampTypes",
          label: "Tipo(s) principal(is) de humidade identificado(s)",
          mode: "multi",
          options: [
            { label: "Condensação", value: "Condensation (poor ventilation)" },
            { label: "Humidade ascendente", value: "Rising damp / capillary action" },
            { label: "Humidade por penetração", value: "Penetrating damp (rain ingress)" },
            { label: "Fuga de canalização", value: "Plumbing leak" },
            { label: "Humidade de construção", value: "Construction moisture" },
            { label: "Sais higroscópicos", value: "Hygroscopic / deliquescent salts" },
            { label: "Condensação intersticial", value: "Interstitial condensation" },
            { label: "Danos por inundação", value: "Flood / post-water damage" },
          ],
        },
        {
          kind: "chips",
          key: "diagnosisConfidence",
          label: "Confiança no diagnóstico",
          mode: "single",
          options: [
            { label: "Alta – evidência clara", value: "High – clear evidence" },
            { label: "Média – provável", value: "Medium – probable" },
            { label: "Baixa – incerto; requer mais investigação", value: "Low – uncertain, needs further investigation" },
          ],
        },
        {
          kind: "chips",
          key: "risingDampIndicators",
          label: "Indicadores de humidade ascendente (se aplicável)",
          mode: "multi",
          options: [
            { label: "Marcas de maré em paredes inferiores", value: "Tide marks on lower walls" },
            { label: "Depósitos de sais em baixo", value: "Salt deposits at low level" },
            { label: "Humidade diminui com a altura", value: "Moisture tapers from base upward" },
            { label: "DPC ausente/falhado", value: "DPC absent/failed" },
            { label: "N/A", value: "N/A" },
          ],
        },
        {
          kind: "chips",
          key: "penetratingIndicators",
          label: "Indicadores de humidade por penetração (se aplicável)",
          mode: "multi",
          options: [
            { label: "Humidade em ombreiras de janelas", value: "Damp at window reveals" },
            { label: "Humidade abaixo da linha de cobertura", value: "Damp below roof line" },
            { label: "Mancha localizada após chuva", value: "Localised patch after rain" },
            { label: "Humidade junto à chaminé", value: "Damp at chimney breast" },
            { label: "N/A", value: "N/A" },
          ],
        },
        {
          kind: "textarea",
          key: "dampDiagNotes",
          label: "Notas adicionais de diagnóstico",
          placeholder:
            "Descreva a lógica do diagnóstico, sinais contraditórios, ou testes usados para diferenciar tipos...",
        },
      ],
    },
    {
      id: 8,
      title: "Defeitos em madeira e materiais",
      desc: "Avalie o estado de elementos de madeira, isolamento e revestimentos de pavimento.",
      questions: [
        {
          kind: "chips",
          key: "timberCondition",
          label: "Estado da madeira (rodapés, vigas, soalhos)",
          mode: "multi",
          options: [
            { label: "Bom – sem defeitos", value: "Sound – no defects" },
            { label: "Apenas manchas superficiais", value: "Surface staining only" },
            { label: "Podridão húmida presente", value: "Wet rot present" },
            { label: "Podridão seca presente", value: "Dry rot present" },
            { label: "Cordões fúngicos observados", value: "Fungal strands observed" },
            { label: "Compromisso estrutural", value: "Structural compromise" },
          ],
        },
        {
          kind: "chips",
          key: "insects",
          label: "Infestação de insetos",
          mode: "single",
          options: [
            { label: "Nenhuma", value: "None" },
            { label: "Caruncho ativo", value: "Active woodworm" },
            { label: "Caruncho inativo", value: "Inactive woodworm" },
            { label: "Térmitas", value: "Termites" },
            { label: "Outro", value: "Other" },
          ],
        },
        {
          kind: "chips",
          key: "insulationCondition",
          label: "Estado do isolamento",
          mode: "single",
          options: [
            { label: "Bom – seco e intacto", value: "Good – dry and intact" },
            { label: "Molhado / saturado", value: "Wet / saturated" },
            { label: "Comprimido e degradado", value: "Compressed and degraded" },
            { label: "Com bolor", value: "Mouldy" },
            { label: "Inexistente / N/A", value: "Not present / N/A" },
          ],
        },
        {
          kind: "chips",
          key: "floorCoverings",
          label: "Estado dos revestimentos de pavimento",
          mode: "multi",
          options: [
            { label: "Seco e em bom estado", value: "Dry and sound" },
            { label: "Húmido sob alcatifa", value: "Damp under carpet" },
            { label: "Húmido sob vinil/laminado", value: "Damp under vinyl/laminate" },
            { label: "Subcapa saturada", value: "Underlay saturated" },
            { label: "A levantar / a borbulhar", value: "Lifting / bubbling" },
          ],
        },
        {
          kind: "chips",
          key: "timberMC",
          label: "Leituras MC% da madeira",
          mode: "single",
          options: [
            { label: "Seco (<18%)", value: "Dry (<18%)" },
            { label: "Ligeiramente elevado (18–20%)", value: "Slightly elevated (18–20%)" },
            { label: "Em risco (20–25%)", value: "At risk (20–25%)" },
            { label: "Risco de podridão húmida (>25%)", value: "Wet rot risk (>25%)" },
            { label: "Não medido", value: "Not measured" },
          ],
        },
        {
          kind: "textarea",
          key: "timberNotes",
          label: "Notas sobre madeira/materiais",
          placeholder:
            "Registe localizações, extensão da degradação, elementos afetados, frutificações, odor a podridão seca...",
        },
      ],
    },
    {
      id: 9,
      title: "Defeitos estruturais e do edifício",
      desc: "Registe fissuras, anomalias estruturais e outros defeitos.",
      questions: [
        {
          kind: "chips",
          key: "cracks",
          label: "Fissuras observadas",
          mode: "multi",
          options: [
            { label: "Sem fissuras", value: "No cracks" },
            { label: "Fissuras capilares – cosméticas", value: "Hairline cracks – cosmetic" },
            { label: "Fissuras diagonais – assentamento", value: "Diagonal cracks – settlement" },
            { label: "Fissuras horizontais – preocupação estrutural", value: "Horizontal cracks – structural concern" },
            { label: "Fissuras verticais", value: "Vertical cracks" },
            { label: "Ativas (a aumentar)", value: "Active (widening)" },
            { label: "Históricas (estáveis)", value: "Historic (stable)" },
          ],
        },
        {
          kind: "chips",
          key: "crackWidth",
          label: "Largura da fissura",
          mode: "single",
          options: [
            { label: "<1mm (fina)", value: "<1mm (fine)" },
            { label: "1–5mm (moderada)", value: "1–5mm (moderate)" },
            { label: "5–15mm (larga – preocupação)", value: "5–15mm (wide – concern)" },
            { label: ">15mm (severa)", value: ">15mm (severe)" },
            { label: "N/A – sem fissuras", value: "N/A – no cracks" },
          ],
        },
        {
          kind: "chips",
          key: "subsidence",
          label: "Sinais de cedência/assentamento",
          mode: "single",
          options: [
            { label: "Nenhum observado", value: "None observed" },
            { label: "Ligeiro – aconselha-se monitorização", value: "Minor – monitoring advised" },
            { label: "Suspeito – investigação necessária", value: "Suspected – investigation needed" },
            { label: "Cedência ativa", value: "Active subsidence" },
          ],
        },
        {
          kind: "chips",
          key: "chimneyDefects",
          label: "Defeitos de chaminé / lareira",
          mode: "multi",
          options: [
            { label: "Sem defeitos / N/A", value: "No defects / N/A" },
            { label: "Humidade na chaminé", value: "Damp at chimney breast" },
            { label: "Depósitos de sais", value: "Salt deposits at breast" },
            { label: "Chapéu/fecho em falta", value: "Capping absent" },
            { label: "Rufos falhados", value: "Failed flashing" },
          ],
        },
        {
          kind: "chips",
          key: "otherStructural",
          label: "Outras preocupações estruturais",
          mode: "multi",
          options: [
            { label: "Nenhuma", value: "None" },
            { label: "Caixa de ar obstruída", value: "Blocked cavity wall" },
            { label: "Suspeita de falha de amarrações", value: "Wall tie failure suspected" },
            { label: "Passagens de serviços (sem selagem)", value: "Service penetrations (unsealed)" },
            { label: "Falha visível de impermeabilização de fundação", value: "Foundation damp-proofing visible failure" },
          ],
        },
        {
          kind: "textarea",
          key: "structuralNotes",
          label: "Notas estruturais",
          placeholder:
            "Descreva padrões e localizações de fissuras, envolvimento de engenheiro, ou preocupações...",
        },
      ],
    },
    {
      id: 10,
      title: "Histórico e intervenções anteriores",
      desc: "Registe tratamentos, reparações e eventos de humidade anteriores.",
      questions: [
        {
          kind: "chips",
          key: "prevTreatments",
          label: "Tratamentos anti-humidade anteriores",
          mode: "multi",
          options: [
            { label: "Sem tratamentos anteriores", value: "No previous treatments" },
            { label: "Injeção química DPC", value: "Chemical DPC injection" },
            { label: "Membranas / tanking", value: "Waterproof membranes / tanking" },
            { label: "Rebocos impermeáveis", value: "Waterproof renders applied" },
            { label: "Tratamento de madeira", value: "Timber treatment (fungicide)" },
            { label: "Drenagem / poço", value: "Drainage / sump installed" },
          ],
        },
        {
          kind: "chips",
          key: "priorSurvey",
          label: "Vistoria/garantia anterior",
          mode: "single",
          options: [
            { label: "Sim – recente (≤ 5 anos)", value: "Yes – recent (within 5 years)" },
            { label: "Sim – antiga", value: "Yes – older" },
            { label: "Garantia em vigor", value: "Guarantee in place" },
            { label: "Sem vistoria anterior", value: "No prior survey" },
          ],
        },
        {
          kind: "chips",
          key: "mouldRemediation",
          label: "Remediação de bolor anterior",
          mode: "multi",
          options: [
            { label: "Nenhuma", value: "None" },
            { label: "Limpeza de superfície", value: "Surface cleaning performed" },
            { label: "Nebulização a seco", value: "Dry fogging / antimicrobial" },
            { label: "Melhoria da ventilação", value: "Ventilation upgrade" },
            { label: "Remoção de materiais", value: "Material removal" },
          ],
        },
        {
          kind: "chips",
          key: "maintenance",
          label: "Histórico de manutenção",
          mode: "multi",
          options: [
            { label: "Manutenção regular", value: "Regular maintenance" },
            { label: "Reparações de telhado feitas", value: "Roof repairs done" },
            { label: "Limpeza de caleiras feita", value: "Gutter cleaning done" },
            { label: "Reboco renovado", value: "Re-rendering done" },
            { label: "Reparações de canalização", value: "Plumbing fixes done" },
            { label: "Sem manutenção", value: "No maintenance" },
          ],
        },
        {
          kind: "textarea",
          key: "historyNotes",
          label: "Notas de histórico",
          placeholder:
            "Datas de trabalhos anteriores, empreiteiros, resultados, datas de inundações...",
        },
      ],
    },
    {
      id: 11,
      title: "Avaliação de risco e impactos",
      desc: "Avalie severidade, riscos de saúde, impactos estruturais e urgência.",
      questions: [
        {
          kind: "chips",
          key: "severity",
          label: "Classificação global de severidade",
          mode: "single",
          options: [
            { label: "🟢 Baixa", value: "Low", className: "sev-low" },
            { label: "🟡 Média", value: "Medium", className: "sev-med" },
            { label: "🟠 Alta", value: "High", className: "sev-high" },
            { label: "🔴 Severa", value: "Severe", className: "sev-sev" },
          ],
        },
        {
          kind: "chips",
          key: "extentAffected",
          label: "Extensão estimada das superfícies afetadas",
          mode: "single",
          options: [
            { label: "<5m² (ligeiro)", value: "<5m² (minor)" },
            { label: "5–20m² (moderado)", value: "5–20m² (moderate)" },
            { label: "20–50m² (significativo)", value: "20–50m² (significant)" },
            { label: ">50m² (extenso)", value: ">50m² (extensive)" },
          ],
        },
        {
          kind: "chips",
          key: "healthRisks",
          label: "Riscos de saúde e segurança identificados",
          mode: "multi",
          options: [
            { label: "Exposição a esporos de bolor", value: "Mould spore exposure" },
            { label: "Risco respiratório", value: "Respiratory risk" },
            { label: "Risco alérgico / asma", value: "Allergic reactions / asthma" },
            { label: "Ácaros do pó", value: "Dust mites (elevated humidity)" },
            { label: "VOCs do bolor", value: "VOCs from mould" },
            { label: "Risco de escorregamento (pavimentos molhados)", value: "Slip risk (wet floors)" },
            { label: "Risco mínimo", value: "Minimal health risk" },
          ],
        },
        {
          kind: "chips",
          key: "vulnerable",
          label: "Ocupantes vulneráveis presentes?",
          mode: "multi",
          options: [
            { label: "Crianças", value: "Children" },
            { label: "Idosos", value: "Elderly" },
            { label: "Asma / respiratório", value: "Asthma / respiratory conditions" },
            { label: "Imunocomprometidos", value: "Immunocompromised" },
            { label: "Nenhum / desconhecido", value: "None / unknown" },
          ],
        },
        {
          kind: "chips",
          key: "structuralRisk",
          label: "Nível de risco estrutural",
          mode: "single",
          options: [
            { label: "Sem risco estrutural", value: "No structural risk" },
            { label: "Risco de enfraquecimento da madeira", value: "Timber weakening risk" },
            { label: "Degradação de materiais em curso", value: "Material degradation ongoing" },
            { label: "Preocupação estrutural ativa", value: "Active structural concern" },
          ],
        },
        {
          kind: "chips",
          key: "urgency",
          label: "Urgência de ação",
          mode: "single",
          options: [
            { label: "Apenas monitorização", value: "Monitor only" },
            { label: "Em 3–6 meses", value: "Within 3–6 months" },
            { label: "Em 1 mês", value: "Within 1 month" },
            { label: "Ação imediata necessária", value: "Immediate action required" },
          ],
        },
      ],
    },
    {
      id: 12,
      title: "Inspeções e métodos utilizados",
      desc: "Registe métodos de inspeção, equipamento e abordagens de verificação.",
      questions: [
        {
          kind: "chips",
          key: "inspectionMethods",
          label: "Métodos de inspeção realizados",
          mode: "multi",
          options: [
            { label: "Inspeção visual", value: "Visual inspection" },
            { label: "Perfilagem de humidade (pinos)", value: "Moisture profiling (pin meter)" },
            { label: "Perfilagem de humidade (não invasivo)", value: "Moisture profiling (non-invasive)" },
            { label: "Termografia", value: "Thermal imaging / IR camera" },
            { label: "Higrómetro / ponto de orvalho", value: "Hygrometer / dew point assessment" },
            { label: "Análise de sais", value: "Salt / hygroscopic analysis" },
            { label: "Testes laboratoriais", value: "Laboratory testing" },
            { label: "Borescópio / endoscópio", value: "Borescope / endoscope" },
            { label: "Amostragem de esporos no ar", value: "Airborne spore sampling" },
            { label: "Registo fotográfico", value: "Photographic evidence log" },
            { label: "Recolha remota (fotos/vídeo)", value: "Client remote intake (photos/video)" },
          ],
        },
        {
          kind: "chips",
          key: "dpcInspection",
          label: "Inspeção do DPC / membrana anti-humidade",
          mode: "single",
          options: [
            { label: "Inspecionado – adequado", value: "Inspected – adequate" },
            { label: "Inspecionado – defeituoso", value: "Inspected – defective" },
            { label: "Inspecionado – ausente", value: "Inspected – absent" },
            { label: "Sem acesso", value: "Not accessible / not inspected" },
          ],
        },
        {
          kind: "chips",
          key: "evidenceQuality",
          label: "Qualidade da evidência fotográfica/vídeo",
          mode: "single",
          options: [
            { label: "Abrangente", value: "Comprehensive – all areas documented" },
            { label: "Parcial", value: "Partial – some areas" },
            { label: "Mínima", value: "Minimal – key areas only" },
            { label: "Nenhuma", value: "None" },
          ],
        },
        {
          kind: "textarea",
          key: "inspectionNotes",
          label: "Notas de métodos de inspeção",
          placeholder:
            "Liste equipamento (marca/modelo), limitações de acesso, áreas não inspecionadas e motivos...",
        },
      ],
    },
    {
      id: 13,
      title: "Segurança, recomendações e remediação",
      desc: "Defina o plano de remediação, tratamentos e prevenção a longo prazo.",
      questions: [
        {
          kind: "chips",
          key: "remediationActions",
          label: "Ações de remediação recomendadas",
          mode: "multi",
          options: [
            { label: "Melhoria de ventilação", value: "Ventilation upgrade (mechanical)" },
            { label: "Desumidificador", value: "Dehumidifier / humidity control" },
            { label: "Injeção química DPC", value: "DPC chemical injection" },
            { label: "Nova membrana DPC", value: "New DPC membrane" },
            { label: "Rejuntamento / substituição de reboco", value: "Re-pointing / render replacement" },
            { label: "Impermeabilização exterior", value: "External waterproofing" },
            { label: "Selagens de janelas/portas", value: "Window / door seal replacement" },
            { label: "Tratamento/substituição de madeira", value: "Timber treatment / replacement" },
            { label: "Drenagem / melhoria de caleiras", value: "Drainage / gutter improvements" },
            { label: "Ajuste do nível do solo", value: "Ground level adjustment" },
            { label: "Melhoria de isolamento", value: "Insulation upgrade (breathable)" },
            { label: "Nebulização a seco", value: "Dry fogging / antimicrobial treatment" },
            { label: "Remoção de materiais", value: "Material removal (drywall / insulation)" },
          ],
        },
        {
          kind: "chips",
          key: "costBand",
          label: "Intervalo estimado de custo",
          mode: "single",
          options: [
            { label: "Baixo (<€1.000)", value: "Low (<€1,000)" },
            { label: "Médio (€1.000–€5.000)", value: "Medium (€1,000–€5,000)" },
            { label: "Alto (€5.000–€15.000)", value: "High (€5,000–€15,000)" },
            { label: "Muito alto (>€15.000)", value: "Very high (>€15,000)" },
          ],
        },
        {
          kind: "chips",
          key: "specialists",
          label: "Especialistas necessários",
          mode: "multi",
          options: [
            { label: "Nenhum", value: "None required" },
            { label: "Engenheiro estrutural", value: "Structural engineer" },
            { label: "Especialista em impermeabilização", value: "Waterproofing specialist" },
            { label: "Especialista em madeira", value: "Timber / dry rot specialist" },
            { label: "Canalizador", value: "Plumber" },
            { label: "Perito/avaliador de edifícios", value: "Building surveyor" },
            { label: "Saúde ambiental", value: "Environmental health" },
          ],
        },
        {
          kind: "chips",
          key: "prevention",
          label: "Medidas de prevenção a longo prazo",
          mode: "multi",
          options: [
            { label: "Plano anual de monitorização", value: "Annual monitoring plan" },
            { label: "Materiais respiráveis", value: "Breathable materials only" },
            { label: "Conselhos de estilo de vida", value: "Lifestyle advice to occupant" },
            { label: "Manutenção regular", value: "Regular gutter/roof maintenance" },
            { label: "Instalação de higrómetro", value: "Hygrometer installation" },
            { label: "Melhoria do edifício (envelope)", value: "Building fabric upgrade" },
          ],
        },
        {
          kind: "textarea",
          key: "finalNotes",
          label: "Notas finais e observações do técnico",
          placeholder:
            "Contexto adicional, comunicação com cliente, ações prioritárias, ou ressalvas para o relatório...",
        },
      ],
    },
  ],
};

export function getSteps(lang: AppLang): Step[] {
  const steps = stepsByLang[lang];
  // Fallback to EN if PT is incomplete during refactor.
  return steps && steps.length === TOTAL_SECTIONS ? steps : stepsByLang.en;
}

